server:
  port: 8888
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        same-site: lax

spring:
  datasource:
    url: jdbc:mysql://192.168.56.11:3306/ec_mall?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Tokyo
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
#  JWT_SECRETはdefault設定値
  secret: ${JWT_SECRET:MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=}
  expiration: 60000
#  60秒 × 1000毫秒 = 6,000,0毫秒　＝　60秒


mybatis:
  configuration:
# database名をJava名に変更します。
    map-underscore-to-camel-case: true

#
#redis:
#