<template><main class="wrap"><h2>カート</h2><el-skeleton v-if="loading" :rows="6" animated /><el-empty v-else-if="!items.length" description="カートは空です"><el-button type="primary" @click="router.push('/products/search')">商品一覧へ</el-button></el-empty><template v-else><el-table :data="items"><el-table-column label="商品" min-width="240"><template #default="{row}"><div class="product"><el-image :src="row.imageUrl" class="thumb" fit="cover" /><span>{{ row.productName }}</span></div></template></el-table-column><el-table-column label="単価" width="130"><template #default="{row}">¥{{ money(row.priceAtAdd) }}</template></el-table-column><el-table-column label="数量" width="180"><template #default="{row}"><el-input-number v-model="row.quantity" :min="1" :max="99" @change="update(row)" /></template></el-table-column><el-table-column label="小計" width="130"><template #default="{row}">¥{{ money(row.priceAtAdd * row.quantity) }}</template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="danger" @click="remove(row.productId)">削除</el-button></template></el-table-column></el-table><div class="footer"><strong>合計金額：¥{{ money(total) }}</strong><div><el-button @click="clear">カートを空にする</el-button><el-button type="primary" @click="router.push('/checkout')">注文へ進む</el-button></div></div></template></main></template>
<script setup>
import { computed,onMounted,ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import { useRouter } from 'vue-router';import { getCart,updateCartItem,removeCartItem,clearCart } from '@/api/cart'
const router=useRouter(),items=ref([]),loading=ref(false),total=computed(()=>items.value.reduce((s,i)=>s+Number(i.priceAtAdd)*i.quantity,0)),money=(v)=>Number(v).toFixed(2)
const fetch=async()=>{loading.value=true;try{items.value=((await getCart()).data.items)||[]}catch(e){ElMessage.error(e.response?.data?.message||'カート情報の取得に失敗しました')}finally{loading.value=false}}
const update=async(row)=>{try{await updateCartItem(row.productId,row.quantity);await fetch()}catch(e){ElMessage.error(e.response?.data?.message||'数量を更新できませんでした');await fetch()}}
const remove=async(id)=>{try{await ElMessageBox.confirm('この商品をカートから削除しますか？','確認',{type:'warning'});await removeCartItem(id);ElMessage.success('削除しました');fetch()}catch(e){if(e!=='cancel')ElMessage.error('削除に失敗しました')}}
const clear=async()=>{try{await ElMessageBox.confirm('カート内の商品をすべて削除しますか？','確認',{type:'warning'});await clearCart();ElMessage.success('カートを空にしました');fetch()}catch(e){if(e!=='cancel')ElMessage.error('処理に失敗しました')}};onMounted(fetch)
</script><style scoped>.wrap{max-width:1100px;margin:auto;padding:24px}.product{display:flex;align-items:center;gap:12px}.thumb{width:48px;height:48px;background:#f4f4f5}.footer{display:flex;justify-content:space-between;align-items:center;margin-top:20px;font-size:18px}</style>
