### 会員ログイン
POST http://localhost:8888/api/auth/login
Content-Type: application/json

{
  "email": "ichiro.suzuki@example.com",
  "password": "test1234"
}

### 会員追加・メールアドレス重複
POST http://localhost:8888/api/members
Content-Type: application/json

{
  "name": "重複テスト",
  "email": "ichiro.suzuki@example.com",
  "age": 30,
  "password": "test1234"
}

### 存在しない会員更新
PUT http://localhost:8888/api/members/999999
Content-Type: application/json

{
  "name": "存在しない会員",
  "email": "not-found@example.com",
  "age": 30
}

### 存在しない会員削除
DELETE http://localhost:8888/api/members/999999

### 会員ログイン・パスワード不正
POST http://localhost:8888/api/auth/login
Content-Type: application/json

{
  "email": "ichiro.suzuki@example.com",
  "password": "wrong-password"
}

### 会員ログイン・メールアドレス不正
POST http://localhost:8888/api/auth/login
Content-Type: application/json

{
  "email": "not-exist@example.com",
  "password": "test1234"
}